name: Deploy FastAPI to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fix DNS issue
        run: sudo systemctl restart systemd-resolved

      - name: Log in to Cloudflare Container Registry
        run: |
          echo "${{ secrets.CF_API_TOKEN }}" | docker login registry.cloudflare.com -u ${{ secrets.CF_ACCOUNT_ID }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t registry.cloudflare.com/${{ secrets.CF_ACCOUNT_ID }}/fastapi-app:latest .
          docker push registry.cloudflare.com/${{ secrets.CF_ACCOUNT_ID }}/fastapi-app:latest

      - name: Deploy to Cloudflare
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/workers/script" \
            -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
            -H "Content-Type: application/javascript" \
            --data-binary @cloudflare-deploy-script.js
