name: Deploy to Cloudflare

on:
  push:
    branches:
      - main  # Change to your deployment branch
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Wrangler CLI
        run: |
          npm install -g wrangler

      - name: Authenticate with Cloudflare
        run: |
          echo "CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t fastapi-app .
          docker tag fastapi-app registry.cloudflare.com/${{ secrets.CF_ACCOUNT_ID }}/fastapi-app
          echo "${{ secrets.CF_API_TOKEN }}" | docker login registry.cloudflare.com -u "${{ secrets.CF_ACCOUNT_ID }}" --password-stdin
          docker push registry.cloudflare.com/${{ secrets.CF_ACCOUNT_ID }}/fastapi-app

      - name: Deploy to Cloudflare
        run: |
          wrangler deploy
